I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/prologo.rpy", line 128, in script
    sr "Espero que não esteja dizendo isso apenas para ganhar o público, querida!"
Exception: Sayer 'sr' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/prologo.rpy", line 128, in script
    sr "Espero que não esteja dizendo isso apenas para ganhar o público, querida!"
  File "C:\Users\User\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\Users\User\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\User\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'sr' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.3.24061702
Star's   
Selection    1.0
Thu Sep 12 13:03:22 2024
